### ISSUE TITLE
Moodle 4.0 Boost theme issue

### ISSUE THREAD

**Issue by vitaliybaran** [marcusgreen/moodle-qtype_gapfill#83] opened 2022-05-06 12:45 UTC
When the quiz containing gapfill questions is opened, both the course index drawer on the left and the blocks drawer on the right are "dead". One can't open them or close. This is not an issue on large screens, however, on regular 15 inch display laptops it becomes a problem when you want to increase space for the question body - these two drawers just stay open or closed.

There are no bugs on the mobile version, though!!! (when you load the quiz say on the phone). Here everything works fine.

**Comment by marcusgreen** [comment] 2022-05-06 20:50
I think I have reproduced it and I will invesstigate further

**Comment by marcusgreen** [comment] 2022-05-09 09:14
I have identified the source of the problem as the use of the jquery.ui library in the plugin which breaks the Moodle 4.0 boost 'dock'. I have not identified the best way of fixing this yet, and will work on finding a solution.

**Comment by marcusgreen** [comment] 2022-05-16 08:42
Converting the drag drop functionality to HTML5 native drag drop seems to be the best way of addressing this issue, and also represents a way to move from using jquery/jqueryui.  Here is the core Moodle recommendation on JQuery
https://docs.moodle.org/dev/jQuery

HTML5 Drag/Drop was not a reasonable option when the plugin was first being written back in 2011 but it is now widely available in browsers.

I have been experimenting with some code to do this and it is working as expected and I am currently testing it against different platforms, e.g. ios/ipad etc. 

I appreciate these details may not mean much if you are not a developer but you can see I am working towards a fix.

**Comment by vitaliybaran** [comment] 2022-05-27 11:51
Thanks for your engagement in this issue. I am an ordinary teacher, so you're right - all these technical terms don't tell me much :). By the way, both panels work fine in the review stage when all the questions are already submitted by the student.

**Comment by marcusgreen** [comment] 2022-05-28 20:11
I have a branch that I am currently testing that seems to work as expected. However I need to test it with as many browsers/mobile devices as I can find. When it is ready for release can I add your name to the release notes as one of the people who has helped with development by reporting issues. You can see how I have done this in the past by browsing this file 
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/master/changelog.md

and looking at each example that starts with My thanks . If that is OK, let me know what name you would like me to use, or if I should use your github name of  vitaliybaran

**Comment by vitaliybaran** [comment] 2022-05-29 00:56
Feel free to use my real name: Vitaliy Baran

**Comment by marcusgreen** [comment] 2022-10-08 08:22
A fix for this is now available in the master branch and in branch
https://github.com/marcusgreen/moodle-qtype_gapfill/tree/gapfill_2.135
And on the moodle.or plugins database
https://moodle.org/plugins/qtype_gapfill
Credit to Vitaly in the readme
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/master/changelog.md
Closing issue

**Closed by marcusgreen** 2022-10-08 08:22 UTC

**Comment by vitaliybaran** [comment] 2022-10-08 09:05
Thanks a lot.

сб, 8 жовт. 2022, 11:22 користувач Marcus Green ***@***.***>
пише:
