### ISSUE TITLE
3.11 - test coverage

### ISSUE THREAD

**Issue by aspark21** [marcusgreen/moodle-qtype_gapfill#72] opened 2021-05-19 17:45 UTC
Warning: $whitelistfolders and $whitelistfiles in coverage.php files are deprecated since Moodle 3.11. Please, replace them with $includelistfolders and $includelistfiles in question/type/gapfill/tests/coverage.php

Occurs towards the end of environment setup for phpunit

**Comment by marcusgreen** [comment] 2021-05-19 18:02
Will do, may release a new version soon to support ionic5/moodle 3.11. The coverage stuff is a bit odd, but very satisfying.

**Comment by aspark21** [comment] 2021-05-19 18:45
Yeah just running our full build, a lot of work to do to get a build without fatal errors during unit test runs, 7 plugins with fatals so far and guessing probably quite a few more. So these warnings are minor in comparison.

Mobile App support sounds cool.

**Comment by marcusgreen** [comment] 2021-05-19 18:53
What were you testing it against, my very recent travis build didn't comment on that
https://travis-ci.org/github/marcusgreen/moodle-qtype_gapfill/builds/771302527

**Comment by aspark21** [comment] 2021-05-19 20:41
Doing full runs of core + all plugins using moodle-docker via jenkins

**Comment by aspark21** [comment] 2021-05-20 08:37
FYI - Had a look through the travis logs - it doesn't seem to record the admin/tool/phpunit/cli/init.php step which is where that was surfaced in our logs

**Comment by marcusgreen** [comment] 2021-05-23 13:11
Just reproduced that message
Warning: $whitelistfolders and $whitelistfiles in coverage.php files are deprecated since Moodle 3.11. Please, replace them with $includelistfolders and $includelistfiles in question/type/gapfill/tests/coverage.php

**Comment by marcusgreen** [comment] 2021-05-23 16:50
Have updated master so those warnings no longer appear. Let me know if it is good for you and then I will close this issue.

**Closed** 2021-06-02 07:00 UTC
