### ISSUE TITLE
HTML tags (sub) does not display in answer

### ISSUE THREAD

**Issue by nadavkav** [marcusgreen/moodle-qtype_gapfill#43] opened 2019-10-10 08:14 UTC
Our Chemistry teachers use formulas that are created by using HTML SUB tag, as the draggable answers, which look fine for the students, but when the students drag them into the answers (HTML INPUT element) they turn into plain text and the formulas break.
![image](https://user-images.githubusercontent.com/231168/66550921-0e843580-eb4f-11e9-9bae-82e46f559493.png)
Is there an easy way to migrate the HTML INPUT element into a DIV or a SPAN, to workaround this issue?

**Comment by marcusgreen** [comment] 2019-10-11 07:57
I have thought about this in the past and I don't see a simple way of doing it. The question type assumes that data is entered into a conventional text area and so will not do any text rendering. The core ddwtos does something different and so will deal with this.  I'd be delighted to look at some code change suggestions though.

**Comment by nadavkav** [comment] 2019-10-11 11:41
How about showing to the student (user) a SPAN with the proper formula display above the INPUT element, and hiding the INPUT element?

1. Copy the SPAN & set the proper INPUT value too
![image](https://user-images.githubusercontent.com/231168/66648725-ec64e300-ec34-11e9-9a6b-c90e6fc9aacc.png)
2. Hide the INPUT element
![image](https://user-images.githubusercontent.com/231168/66648781-13bbb000-ec35-11e9-9b1e-31c7d0a81977.png)

Does it make sense? is it difficult to add to the code?

**Comment by jaro78-wgg** [comment] 2022-07-14 20:03
gh pr checkout 77

**Comment by Amrita1991** [comment] 2022-09-08 13:10
We have noticed this problem too. In our case it is more severe since answers containing superscript/subscript is getting evaluated as wrong although students are dragging and dropping the correct answer.
The cause for this is, that when the code is comparing the user-given answer and the correct answer the HTML tag is stripped out in the former. Also if we are using subscript/superscript in Distractions, they are not displayed correctly during the course

**Comment by marcusgreen** [comment] 2022-11-16 22:20
Closing for the same reason as this https://github.com/marcusgreen/moodle-qtype_gapfill/issues/91

**Closed by marcusgreen** 2022-11-16 22:20 UTC

**Comment by nadavkav** [comment] 2022-11-17 12:40
@marcusgreen , we recently fixed this, and I would love to upload a fix, if it is still relevant

**Comment by marcusgreen** [comment] 2022-11-17 15:25
Always interested in ideas from you... send me, contact me,create pull, anyway you can. About to embark on testing for 4.1, only have one thing scheduled for next release.
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/master/changelog.md

**Comment by Amrita1991** [comment] 2022-11-18 13:16
Please let me know too if the solution from @nadavkav is implementable.
