### ISSUE TITLE
gapfill question type - Moodle blocks appear under question and run down the page.

### ISSUE THREAD

**Issue by hovez701** [marcusgreen/moodle-qtype_gapfill#62] opened 2020-10-19 10:41 UTC
Hi Marcus,

The gapfill question type appears to be throwing off the display of Moodle blocks on UCL Moodle. The blocks are appearing underneath Quiz questions, overlayed on top of subsequent questions, rather than on the right hand side. See picture.
<img width="754" alt="2020-10-19 11_22_49-Gapfill quiz test" src="https://user-images.githubusercontent.com/56312408/96440152-7871f900-11ff-11eb-8f00-4cf5a5ba8048.png">

This issue only occurs with the gapfill question type where display answers is set to dragdrop. Changing displays answers to dropdown resolves the issue.
<img width="910" alt="gapfill good display" src="https://user-images.githubusercontent.com/56312408/96440251-9b9ca880-11ff-11eb-8969-fe1faf94ec55.png">

Could you advise what might be causing this issue?

Many thanks,
Eliot
UCL Digital Education

Moodle
Moodle 3.7.8 (Build: 20200914)
Adaptable theme. I have also tested on Classic theme and the issue persists.
Gapfill question version: 2020091100

Viewing on
Firefox: Version 81.0.2 (64-bit)
Chrome: Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by marcusgreen** [comment] 2020-10-19 10:46
Thanks for the feedback. I have just installed adaptable so that will make testing easier. Can you confirm it happens with Boost?

**Comment by hovez701** [comment] 2020-10-19 10:58
Yes it appears to happen on Boost as well.

**Comment by marcusgreen** [comment] 2020-10-19 11:04
Have just reproduced. Will investigate further.

**Comment by marcusgreen** [comment] 2020-10-19 11:13
Can you message me directly at marcusgreen at mailbox.org

**Comment by marcusgreen** [comment] 2020-10-19 16:10
I have deleted a line that contained a div terminator 
https://github.com/marcusgreen/moodle-qtype_gapfill/commit/62c5be85d2a458d88f2de257519f15b91ae64cc5#diff-e82e7ce1e17af09c0cd0f5fee5930434efabb50487fa59a889bc3ba36503c1b8
I have briefly tested through the browser and via the mobile app and this appears to fix the issue. I have seen a similar issue previously so I am reasonably confident that this was the cause. 

Copy this file to add the fix to an existing installation.
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/master/renderer.php
Or wait till further testing and a release to the plugins database.
Marcus

**Comment by marcusgreen** [comment] 2020-10-19 21:43
I have conducted further manual tests at vledevelop.co.uk/mdl39 with the modified a renderer.php and the modification appears to have worked without introducing any new issues. I will continue to test.

**Comment by marcusgreen** [comment] 2020-10-21 21:54
I have investigated further and I suspect that a comment in a recent release 'The optionsaftertext setting did not work on Mobile, fixed by adding a missing a closing div tag' might be the source of the problem, so I will test the code in Mobile. I will need to re-check out the updated code in mobile.

**Comment by marcusgreen** [comment] 2020-10-21 22:37
Now understand a bit more about what caused the problem and the issue that the simple deletion of closing tag would cause. Will work on further as soon as I can.

**Comment by marcusgreen** [comment] 2020-10-26 11:04
I anticipate releasing the update to the plugins database very soon.

**Comment by marcusgreen** [comment] 2020-10-26 11:16
By soon I mean in less than 24 hours

**Comment by marcusgreen** [comment] 2020-11-05 22:48
Release version 2.10 which fixes this.

**Closed by marcusgreen** 2020-11-05 22:48 UTC
